# Bucket 1
[invoke.createBucket1Epoch]
target="Foil"
func="createEpoch"
from="<%= settings.deployer %>"
args=[
  "<%= settings.marketStartingTime %>", 
  "<%= settings.marketEndingTime %>", 
  "<%= settings.initialPricePointFive %>",
  "<%= settings.baseAssetTickZero %>", 
  "<%= settings.baseAssetTickOne %>",  
  "<%= settings.bucket1Name %>"
]
depends=["invoke.initializeMarket"]

# Bucket 2
[invoke.createBucket2Epoch]
target="Foil"
func="createEpoch"
from="<%= settings.deployer %>"
args=[
  "<%= settings.marketStartingTime %>", 
  "<%= settings.marketEndingTime %>", 
  "<%= settings.initialPricePointFive %>",
  "<%= settings.baseAssetTickZero %>", 
  "<%= settings.baseAssetTickOne %>",  
  "<%= settings.bucket2Name %>"
]
depends=["invoke.initializeMarket"]

# Bucket 3
[invoke.createBucket3Epoch]
target="Foil"
func="createEpoch"
from="<%= settings.deployer %>"
args=[
  "<%= settings.marketStartingTime %>", 
  "<%= settings.marketEndingTime %>", 
  "<%= settings.initialPricePointFive %>",
  "<%= settings.baseAssetTickZero %>", 
  "<%= settings.baseAssetTickOne %>",  
  "<%= settings.bucket3Name %>"
]
depends=["invoke.initializeMarket"]

# Bucket 4
[invoke.createBucket4Epoch]
target="Foil"
func="createEpoch"
from="<%= settings.deployer %>"
args=[
  "<%= settings.marketStartingTime %>", 
  "<%= settings.marketEndingTime %>", 
  "<%= settings.initialPricePointFive %>",
  "<%= settings.baseAssetTickZero %>", 
  "<%= settings.baseAssetTickOne %>",  
  "<%= settings.bucket4Name %>"
]
depends=["invoke.initializeMarket"]

# Bucket 5
[invoke.createBucket5Epoch]
target="Foil"
func="createEpoch"
from="<%= settings.deployer %>"
args=[
  "<%= settings.marketStartingTime %>", 
  "<%= settings.marketEndingTime %>", 
  "<%= settings.initialPricePointFive %>",
  "<%= settings.baseAssetTickZero %>", 
  "<%= settings.baseAssetTickOne %>",  
  "<%= settings.bucket5Name %>"
]
depends=["invoke.initializeMarket"]

# Nominate safe owner after creation of epoch
[invoke.transferOwnership]
target="Foil"
func="transferOwnership"
from="<%= settings.deployer %>"
args=[
  "<%= settings.owner %>"
]
depends=[
  "invoke.createBucket1Epoch", 
  "invoke.createBucket2Epoch", 
  "invoke.createBucket3Epoch", 
  "invoke.createBucket4Epoch", 
  "invoke.createBucket5Epoch"
]

