[var.settings]
deployer="0xdb5af497a73620d881561edb508012a5f84e9ba2"
owner="0x66aB20e98fcACfadB298C0741dFddA92568B5826"
feeRate = "10000" # 1%
assertionLiveness = "21600"
bondAmount = "500000000"
minTradeSize = "10000"
claimStatement = "<%= stringToHex('replece me when included') %>"


# Integration addresses
optimisticOracleV3 = "0x2aBf1Bd76655de80eDB3086114315Eec75AF500c" # UMA Optimistic Oracle V3 
uniswapPositionManager = "0x03a520b32C04BF3bEEf7BEb72E919cf822Ed34f1" # Uniswap V3 NonfungiblePositionManager 
uniswapSwapRouter = "0xAf5ead464aFFB12dD4CDFB98c9D2C490194FE5d0" # Using our deployed SwapRouter // "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45" # Uniswap V3 SwapRouter 
uniswapQuoter = "0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a" # Uniswap V3 QuoterV2 

# well known ticks 
baseAssetTickZero = "-92200" # baseAssetMinPriceTick: 0.01
baseAssetTickOne = "0"  # baseAssetMaxPriceTick: 1

# well known price 
initialPricePointFive = "56022770974786143748341366784" # 0.5000000000000001

# tokens
sUSDS = "0x5875eee11cf8398102fdad704c9e96607675467a"
USDC = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
depends = []

[deploy.ConfigurationModule]
artifact="ConfigurationModule"
args=["<%= settings.deployer %>"]

[deploy.LiquidityModule]
artifact="LiquidityModule"

[deploy.UMASettlementModule]
artifact="UMASettlementModule"

[deploy.TradeModule]
artifact="TradeModule"

[deploy.NftModule]
artifact="NftModule"

[deploy.ViewsModule]
artifact="ViewsModule"

[deploy.ERC165Module]
artifact="ERC165Module"

[deploy.SettlementModule]
artifact="SettlementModule"

[router.Foil]
contracts=[
  "ConfigurationModule",
  "LiquidityModule",
  "UMASettlementModule",
  "TradeModule",
  "NftModule",
  "ViewsModule",
  "ERC165Module",
  "SettlementModule"
]
highlight=true

[invoke.initializeMarket]
target="Foil"
func="initializeMarket"
from="<%= settings.deployer %>"
args=[
  "<%= settings.deployer %>",
  "<%= settings.sUSDS %>",
  [],
  "<%= zeroAddress %>",
  "<%= settings.minTradeSize %>",
  { feeRate = "<%= settings.feeRate %>", assertionLiveness= "<%= settings.assertionLiveness %>", bondCurrency = "<%= settings.USDC %>", bondAmount = "<%= settings.bondAmount %>", claimStatement = "<%= settings.claimStatement %>", uniswapPositionManager = "<%= settings.uniswapPositionManager %>", uniswapSwapRouter = "<%= settings.uniswapSwapRouter %>", uniswapQuoter = "<%= settings.uniswapQuoter %>", optimisticOracleV3 = "<%= settings.optimisticOracleV3 %>" }
]
depends=["router.Foil"]

