databases:
  - name: database
    databaseName: foil
    plan: pro-4gb

services:
  - name: web-service
    type: web
    env: node
    plan: pro
    buildCommand: chmod +x render-build.sh && ./render-build.sh && pnpm --filter @sapience/api install
    startCommand: pnpm --filter @sapience/api start:service
    autoDeploy: true
    repo: https://github.com/sapiencexyz/sapience
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString

  - name: background-worker
    type: worker
    env: node
    plan: standard
    buildCommand: chmod +x render-build.sh && ./render-build.sh && pnpm --filter @sapience/api install && pnpm --filter @sapience/api prisma:generate
    startCommand: pnpm --filter @sapience/api start:worker
    autoDeploy: true
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString

  - name: candle-cache-builder
    type: worker
    env: node
    plan: pro
    buildCommand: chmod +x render-build.sh && ./render-build.sh && pnpm --filter @sapience/api install
    startCommand: pnpm --filter @sapience/api start:candle-cache
    autoDeploy: true
    repo: https://github.com/sapiencexyz/sapience
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString