databases:
  - name: database
    databaseName: foil
    plan: pro-4gb

services:
  - name: web-service
    type: web
    env: node
    plan: pro
    buildCommand: chmod +x render-build.sh && ./render-build.sh && pnpm --filter @foil/api install
    startCommand: pnpm --filter @foil/api start:service
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
    repo: https://github.com/foilxyz/foil
    branch: main

  - name: background-worker
    type: worker
    env: node
    plan: standard
    buildCommand: chmod +x render-build.sh && ./render-build.sh && pnpm --filter @foil/api install
    startCommand: pnpm --filter @foil/api start:worker
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
    repo: https://github.com/foilxyz/foil
    branch: main
