name="foil-test"
version="<%= package.version %>"
privateSourceCode=true

[var.settings]
owner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
# Vault Settings
vaultName="Foil Vault"
vaultSymbol = "FVLT"
duration = "2419200" # 28 days in seconds
depends = []

[clone.Uniswap]
source="uniswap:3.0.1"
target="foil@uniswap"

[clone.CollateralAsset]
source="mintable-token@permissionless-mint"
target="foil@test-collateral-asset"
var.symbol="wstETH"

[clone.BondCurrency]
source="mintable-token@permissionless-mint"
target="foil@test-bond-currency"
var.symbol="USDC"
var.decimals = "6"

[clone.UMA]
source="uma-oov3"
target="foil@uma-mock"
options.defaultCurrency = "<%= BondCurrency.Token.address %>"
options.minimumBond = "0"

[deploy.ConfigurationModule]
artifact="ConfigurationModule"
args=["0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"]

[deploy.LiquidityModule]
artifact="LiquidityModule"

[deploy.UMASettlementModule]
artifact="UMASettlementModule"

[deploy.TradeModule]
artifact="TradeModule"

[deploy.NftModule]
artifact="NftModule"

[deploy.ViewsModule]
artifact="ViewsModule"

[deploy.ERC165Module]
artifact="ERC165Module"

[deploy.SettlementModule]
artifact="SettlementModule"

[deploy.ExposedInternalFunctions]
artifact="ExposedInternalFunctions"

[deploy.MockVault]
artifact="MockVault"

[router.Foil]
contracts=[
  "ConfigurationModule",
  "LiquidityModule",
  "UMASettlementModule",
  "TradeModule",
  "NftModule",
  "ViewsModule",
  "ERC165Module",
  "ExposedInternalFunctions",
  "SettlementModule"
]
highlight=true

[deploy.FoilVault]
artifact="FoilVault"
from="<%= settings.owner %>"
args=[ "<%= settings.vaultName %>", "<%= settings.vaultSymbol %>", "<%= Foil.address %>", "<%= CollateralAsset.Token.address %>", "<%= settings.duration %>"]
depends = ['router.Foil', 'clone.CollateralAsset', 'var.settings']
