name="foil"
version="0.7"

[var.settings]
owner="0xE006B58cA5aB7ba53863012dc3067A14b965C1da"
startTime = "1722270000" # Mon Jul 29 2024 16:20:00 GMT+0000
endTime = "1725195600" # Sunday, September 1, 2024 9:00:00 AM GMT-04:00
baseAssetMinPriceTick = "5200" # 1.709
baseAssetMaxPriceTick = "28200" # 17.09
feeRate = "10000" # 1%
startingSqrtPriceX96 = "146497135921788803112962621440" # 3.419
assertionLiveness = "3600"
bondAmount = "5000000000"
priceUnit = "<%= formatBytes32String('wstGwei/gas') %>"
optimisticOracleV3 = "0xFd9e2642a170aDD10F53Ee14a93FcF2F31924944"
depends = []

# [pull.Uniswap]
# source="uniswap"

[pull.wstETH]
source="wsteth-token"

[pull.USDC]
source="usdc-token"

[deploy.ReentrancyGuard]
artifact = "ReentrancyGuard"

[deploy.EpochConfigurationModule]
artifact="EpochConfigurationModule"
libraries.ReentrancyGuard="<%= contracts.ReentrancyGuard.address %>"

[deploy.EpochLiquidityModule]
artifact="EpochLiquidityModule"

[deploy.EpochUMASettlementModule]
artifact="EpochUMASettlementModule"

[deploy.EpochTradeModule]
artifact="EpochTradeModule"

[deploy.EpochNftModule]
artifact="EpochNftModule"

[deploy.EpochViewsModule]
artifact="EpochViewsModule"

[deploy.EpochERC165Module]
artifact="EpochERC165Module"

[router.Foil]
contracts=[
  "EpochConfigurationModule",
  "EpochLiquidityModule",
  "EpochUMASettlementModule",
  "EpochTradeModule",
  "EpochNftModule",
  "EpochViewsModule",
  "EpochERC165Module"
]

[invoke.initializeMarket]
target="Foil"
func="initializeMarket"
args=[
  "<%= settings.owner %>",
  "<%= imports.wstETH.contracts.Token.address %>",
  "0x1238536071E1c677A632429e3655c799b22cDA52",
  "0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD",
  "<%= settings.optimisticOracleV3 %>",
  { baseAssetMinPriceTick = "<%= settings.baseAssetMinPriceTick %>", baseAssetMaxPriceTick = "<%= settings.baseAssetMaxPriceTick %>", feeRate = "<%= settings.feeRate %>", assertionLiveness= "<%= settings.assertionLiveness %>", bondCurrency = "<%= imports.USDC.contracts.Token.address %>", bondAmount = "<%= settings.bondAmount %>", priceUnit = "<%= settings.priceUnit %>" }
]
depends=["router.Foil"]

[invoke.createEpoch]
target="Foil"
from = "<%= settings.owner %>"
func="createEpoch"
args=[
  "<%= settings.startTime %>",
  "<%= settings.endTime %>",
  "<%= settings.startingSqrtPriceX96 %>"
]
depends=["invoke.initializeMarket"]