name="foil"
version="<%= package.version %>"
privateSourceCode=true

[var.settings]
owner="0xE006B58cA5aB7ba53863012dc3067A14b965C1da"
startTime = "<%= parseInt(timestamp) + 600 %>"
endTime = "<%= parseInt(timestamp) + 600 + 604800 %>"
baseAssetMinPriceTick = "16000" # 5
baseAssetMaxPriceTick = "39000" # 50
feeRate = "10000" # 1%
startingSqrtPriceX96 = "146497135921788803112962621440" # 3.419
assertionLiveness = "21600" # 6 hours
bondAmount = "5000000000"
claimStatement = "<%= stringToHex('The sum of gas used divided by the sum of base fees paid on Ethereum Mainnet across all blocks, divided by the wstETH/ETH ratio at the end of the period, represented with 18 decimal places') %>"
optimisticOracleV3 = "0xFd9e2642a170aDD10F53Ee14a93FcF2F31924944"
callbackRecipient = "0x0000000000000000000000000000000000000000"
minTradeSize = "10000"
depends = []

# [pull.Uniswap]
# source="uniswap"

[pull.wstETH]
source="wsteth-token"

[pull.USDC]
source="usdc-token"

[deploy.ConfigurationModule]
artifact="ConfigurationModule"
args=["<%= settings.owner %>"]

[deploy.LiquidityModule]
artifact="LiquidityModule"

[deploy.UMASettlementModule]
artifact="UMASettlementModule"

[deploy.TradeModule]
artifact="TradeModule"

[deploy.NftModule]
artifact="NftModule"

[deploy.ViewsModule]
artifact="ViewsModule"

[deploy.ERC165Module]
artifact="ERC165Module"

[deploy.SettlementModule]
artifact="SettlementModule"

[router.Foil]
contracts=[
  "ConfigurationModule",
  "LiquidityModule",
  "UMASettlementModule",
  "TradeModule",
  "NftModule",
  "ViewsModule",
  "ERC165Module",
  "SettlementModule"
]
highlight=true

[invoke.initializeMarket]
target="Foil"
func="initializeMarket"
from="<%= settings.owner %>"
args=[
  "<%= settings.owner %>",
  "<%= imports.wstETH.contracts.Token.address %>",
  [],
  "<%= settings.callbackRecipient %>",
  "<%= settings.minTradeSize %>",
  { baseAssetMinPriceTick = "<%= settings.baseAssetMinPriceTick %>", baseAssetMaxPriceTick = "<%= settings.baseAssetMaxPriceTick %>", feeRate = "<%= settings.feeRate %>", assertionLiveness= "<%= settings.assertionLiveness %>", bondCurrency = "<%= imports.USDC.contracts.Token.address %>", bondAmount = "<%= settings.bondAmount %>", claimStatement = "<%= settings.claimStatement %>", uniswapPositionManager = "0x1238536071E1c677A632429e3655c799b22cDA52", uniswapSwapRouter = "0x65669fe35312947050c450bd5d36e6361f85ec12", uniswapQuoter = "0xEd1f6473345F45b75F8179591dd5bA1888cf2FB3", optimisticOracleV3 = "<%= settings.optimisticOracleV3 %>" }
]
depends=["router.Foil"]

[invoke.createEpoch]
target="Foil"
from = "<%= settings.owner %>"
func="createEpoch"
args=[
  "<%= settings.startTime %>",
  "<%= settings.endTime %>",
  "<%= settings.startingSqrtPriceX96 %>",
  "4"
]
depends=["invoke.initializeMarket"]