name="foil"
version="<%= package.version %>"
privateSourceCode=true

[var.settings]
owner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
startTime = "<%= parseInt(timestamp) %>"
endTime = "<%= parseInt(timestamp) + 604800 %>"
baseAssetMinPriceTick = "16000" # 5
baseAssetMaxPriceTick = "39000" # 50
feeRate = "10000" # 1%
startingSqrtPriceX96 = "146497135921788803112962621440" # 3.419
assertionLiveness = "21600" # 6 hours
bondAmount = "5000000000"
claimStatement = "<%= stringToHex('The sum of gas used divided by the sum of base fees paid on Ethereum Mainnet across all blocks, divided by the wstETH/ETH ratio at the end of the period, represented with 18 decimal places') %>"
callbackRecipient = "0x0000000000000000000000000000000000000000"
minTradeSize = "10000"
depends=[]

[clone.UMA]
source="uma-oov3"
target="foil@uma-mock"
options.defaultCurrency = "<%= BondCurrency.Token.address %>"
options.minimumBond = "0"

[clone.Uniswap]
source="uniswap:3.0.1"
target="foil@uniswap"

[clone.CollateralAsset]
source="mintable-token@permissionless-mint"
target="foil@test-collateral-asset"
var.symbol="wstETH"

[clone.BondCurrency]
source="mintable-token@permissionless-mint"
target="foil@test-bond-currency"
var.symbol="USDC"
var.decimals = "6"

[deploy.ConfigurationModule]
artifact="ConfigurationModule"
args=["<%= settings.owner %>"]

[deploy.LiquidityModule]
artifact="LiquidityModule"

[deploy.UMASettlementModule]
artifact="UMASettlementModule"

[deploy.TradeModule]
artifact="TradeModule"

[deploy.NftModule]
artifact="NftModule"

[deploy.ViewsModule]
artifact="ViewsModule"

[deploy.ERC165Module]
artifact="ERC165Module"

[deploy.SettlementModule]
artifact="SettlementModule"

[router.Foil]
contracts=[
  "ConfigurationModule",
  "LiquidityModule",
  "UMASettlementModule",
  "TradeModule",
  "NftModule",
  "ViewsModule",
  "ERC165Module",
  "SettlementModule"
]
highlight=true

[invoke.initializeMarket]
target="Foil"
func="initializeMarket"
from="<%= settings.owner %>"
args=[
  "<%= settings.owner %>",
  "<%= imports.CollateralAsset.contracts.Token.address %>",
  [],
  "<%= settings.callbackRecipient %>",
  "<%= settings.minTradeSize %>",
  { baseAssetMinPriceTick = "<%= settings.baseAssetMinPriceTick %>", baseAssetMaxPriceTick = "<%= settings.baseAssetMaxPriceTick %>", feeRate = "<%= settings.feeRate %>", assertionLiveness= "<%= settings.assertionLiveness %>", bondCurrency = "<%= imports.BondCurrency.contracts.Token.address %>", bondAmount= "<%= settings.bondAmount %>", claimStatement= "<%= settings.claimStatement %>",  uniswapPositionManager =  "<%= imports.Uniswap.contracts.NonfungiblePositionManager.address %>", uniswapSwapRouter = "<%= imports.Uniswap.contracts.SwapRouter.address %>", uniswapQuoter = "<%= imports.Uniswap.contracts.QuoterV2.address %>", optimisticOracleV3 = "<%= imports.UMA.contracts.OptimisticOracleV3.address %>" }
]
depends=["router.Foil"]


[invoke.createEpoch]
target="Foil"
func="createEpoch"
from="<%= settings.owner %>"
args=[
  "<%= settings.startTime %>",
  "<%= settings.endTime %>",
  "<%= settings.startingSqrtPriceX96 %>",
  "4"
]
depends=["invoke.initializeMarket"]

[invoke.gimmeTokens]
target="CollateralAsset.Token"
func="mint"
args=["<%= parseEther('1000') %>", "<%= settings.owner %>"]
depends=["clone.CollateralAsset"]