name="foil-vault-test"
version="<%= package.version %>"
privateSourceCode=true

[var.settings]
owner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
# Vault Settings
vaultName="Foil Vault"
vaultSymbol = "FVLT"
duration = "2419200" # 28 days in seconds 
initialSqrtPriceX96 = "146497135921788803112962621440" # 3.419
initialStartTime = "<%= parseInt(timestamp) + 600 %>"
# Epoch Settings
startTime = "<%= parseInt(timestamp) + 600 %>"
endTime = "<%= parseInt(timestamp) + 600 + 604800 %>"
baseAssetMinPriceTick = "5200" # 1.709
baseAssetMaxPriceTick = "28200" # 17.09
feeRate = "10000" # 1%
startingSqrtPriceX96 = "146497135921788803112962621440" # 3.419
assertionLiveness = "21600" # 6 hours
bondAmount = "5000000000"
priceUnit = "<%= formatBytes32String('wstGwei/gas') %>"
depends = []

[clone.Uniswap]
source="uniswap:3.0.1"
target="foil@uniswap"

[clone.CollateralAsset]
source="mintable-token@permissionless-mint"
target="foil@test-collateral-asset"
var.symbol="wstETH"

[clone.BondCurrency]
source="mintable-token@permissionless-mint"
target="foil@test-bond-currency"
var.symbol="USDC"
var.decimals = "6"

[clone.UMA]
source="uma-oov3"
target="foil@uma-mock"
options.defaultCurrency = "<%= BondCurrency.Token.address %>"
options.minimumBond = "0"

[deploy.ConfigurationModule]
artifact="ConfigurationModule"
args=["0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"]

[deploy.LiquidityModule]
artifact="LiquidityModule"

[deploy.UMASettlementModule]
artifact="UMASettlementModule"

[deploy.TradeModule]
artifact="TradeModule"

[deploy.NftModule]
artifact="NftModule"

[deploy.ViewsModule]
artifact="ViewsModule"

[deploy.ERC165Module]
artifact="ERC165Module"

[deploy.ExposedInternalFunctions]
artifact="ExposedInternalFunctions"

[deploy.SettlementModule]
artifact="SettlementModule"

[router.Foil]
contracts=[
  "ConfigurationModule",
  "LiquidityModule",
  "UMASettlementModule",
  "TradeModule",
  "NftModule",
  "ViewsModule",
  "ERC165Module",
  "ExposedInternalFunctions",
  "SettlementModule"
]
highlight=true

[deploy.Vault]
artifact="Vault"
from="<%= settings.owner %>"
args=[ "<%= settings.vaultName %>", "<%= settings.vaultSymbol %>", "<%= Foil.address %>", "<%= CollateralAsset.Token.address %>", "<%= settings.duration %>", "<%= settings.initialSqrtPriceX96 %>", "<%= settings.initialStartTime %>"]
depends = ['router.Foil', 'clone.CollateralAsset', 'var.settings']

[invoke.initializeMarket]
target="Foil"
from="<%= settings.owner %>"
func="initializeMarket"
args=[
  "<%= Vault.address %>",
  "<%= CollateralAsset.Token.address %>",
  { baseAssetMinPriceTick = "<%= settings.baseAssetMinPriceTick %>", baseAssetMaxPriceTick = "<%= settings.baseAssetMaxPriceTick %>", feeRate = "<%= settings.feeRate %>", assertionLiveness= "<%= settings.assertionLiveness %>", bondCurrency = "<%= BondCurrency.Token.address %>", bondAmount = "<%= settings.bondAmount %>", priceUnit = "<%= settings.priceUnit %>", uniswapPositionManager = "<%= Uniswap.NonfungiblePositionManager.address %>", uniswapSwapRouter = "<%= Uniswap.SwapRouter.address %>", uniswapQuoter = "<%= Uniswap.QuoterV2.address %>", optimisticOracleV3 = "<%= UMA.OptimisticOracleV3.address %>" }
]
depends=["router.Foil", "deploy.Vault"]


[invoke.initializeEpoch]
target="Vault"
from="<%= settings.owner %>"
func="initializeEpoch"
depends=["invoke.initializeMarket"]
