name="sapience"
version="1.1.0"

[var.settings]
owner="0xdb5Af497A73620d881561eDb508012A5f84e9BA2"
baseAssetMinPriceTick = "16000" # 5
baseAssetMaxPriceTick = "39000" # 50
feeRate = "10000" # 1%
startingSqrtPriceX96 = "345347553882095649185803010048" # 19
assertionLiveness = "21600"
bondAmount = "5000000000"
claimStatement = "<%= stringToHex('The sum of gas used divided by the sum of base fees paid on Ethereum Mainnet across all blocks, divided by the wstETH/ETH ratio at the end of the period, represented with 18 decimal places') %>"
optimisticOracleV3 = "0xFd9e2642a170aDD10F53Ee14a93FcF2F31924944"
minTradeSize = "10000"
depends = []

# [pull.Uniswap]
# source="uniswap"

[pull.wstETH]
source="wsteth-token"

[pull.USDC]
source="usdc-token"

[deploy.ConfigurationModule]
artifact="ConfigurationModule"

[deploy.LiquidityModule]
artifact="LiquidityModule"

[deploy.TradeModule]
artifact="TradeModule"

[deploy.ViewsModule]
artifact="ViewsModule"

[deploy.SettlementModule]
artifact="SettlementModule"

[deploy.UMASettlementModule]
artifact="UMASettlementModule"

[deploy.NftModule]
artifact="NftModule"

[deploy.ERC165Module]
artifact="ERC165Module"

[router.Sapience]
contracts=[
  "ConfigurationModule",
  "LiquidityModule",
  "UMASettlementModule",
  "TradeModule",
  "NftModule",
  "ViewsModule",
  "ERC165Module",
  "SettlementModule"
]
highlight=true

[invoke.initializeMarketGroup]
target="Sapience"
func="initializeMarketGroup"
from="<%= settings.owner %>"
args=[
  "<%= settings.owner %>",
  "<%= imports.wstETH.contracts.Token.address %>",
  [],
  "<%= settings.minTradeSize %>",
  "false",
  { feeRate = "<%= settings.feeRate %>", assertionLiveness= "<%= settings.assertionLiveness %>", bondCurrency = "<%= imports.USDC.contracts.Token.address %>", bondAmount = "<%= settings.bondAmount %>", uniswapPositionManager = "0x1238536071E1c677A632429e3655c799b22cDA52", uniswapSwapRouter = "0x65669fe35312947050c450bd5d36e6361f85ec12", uniswapQuoter = "0xEd1f6473345F45b75F8179591dd5bA1888cf2FB3", optimisticOracleV3 = "<%= settings.optimisticOracleV3 %>" }
]
depends=["router.Sapience"]
