name="foil-test"
version="1.0.4"

[var.settings]
owner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" #1 from anvil
owner2 = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8" #2 from anvil
# Vault Settings
vaultName="Foil Vault"
vaultSymbol = "FVLT"
lowerBoundMultiplier = "0.5773502691896257" # sqrt(1/3) 
upperBoundMultiplier = "1.7320508075688772" # sqrt(3)
duration = "2419200" # 28 days in seconds
totalVaults = "1"
claimStatement = "<%= stringToHex('wstGwei/gas') %>"
depends = []

[clone.Uniswap]
source="uniswap:3.0.1"
target="foil@uniswap"

[clone.CollateralAsset]
source="mintable-token@permissionless-mint"
target="foil@test-collateral-asset"
var.symbol="wstETH"

[clone.BondCurrency]
source="mintable-token@permissionless-mint"
target="foil@test-bond-currency"
var.symbol="USDC"
var.decimals = "6"

[clone.UMA]
source="uma-oov3"
target="foil@uma-mock"
options.defaultCurrency = "<%= BondCurrency.Token.address %>"
options.minimumBond = "0"

[deploy.ConfigurationModule]
artifact="ConfigurationModule"
args=["0x70997970C51812dc3A010C7d01b50e0d17dc79C8"]

[deploy.LiquidityModule]
artifact="LiquidityModule"

[deploy.UMASettlementModule]
artifact="UMASettlementModule"

[deploy.TradeModule]
artifact="TradeModule"

[deploy.NftModule]
artifact="NftModule"

[deploy.ViewsModule]
artifact="ViewsModule"

[deploy.ERC165Module]
artifact="ERC165Module"

[deploy.SettlementModule]
artifact="SettlementModule"

[deploy.ExposedInternalFunctions]
artifact="ExposedInternalFunctions"

[deploy.MockVault]
artifact="MockVault"

[router.Foil]
from="<%= settings.owner2 %>"
contracts=[
  "ConfigurationModule",
  "LiquidityModule",
  "UMASettlementModule",
  "TradeModule",
  "NftModule",
  "ViewsModule",
  "ERC165Module",
  "ExposedInternalFunctions",
  "SettlementModule"
]
highlight=true

[router.Foil2]
from="<%= settings.owner2 %>"
contracts=[
  "ConfigurationModule",
  "LiquidityModule",
  "UMASettlementModule",
  "TradeModule",
  "NftModule",
  "ViewsModule",
  "ERC165Module",
  "ExposedInternalFunctions",
  "SettlementModule"
]
highlight=true

[router.Foil3]
from="<%= settings.owner2 %>"
contracts=[
  "ConfigurationModule",
  "LiquidityModule",
  "UMASettlementModule",
  "TradeModule",
  "NftModule",
  "ViewsModule",
  "ERC165Module",
  "ExposedInternalFunctions",
  "SettlementModule"
]
highlight=true

[deploy.Vault]
artifact="Vault"
from="<%= settings.owner2 %>"
args=[ "<%= settings.vaultName %>", "<%= settings.vaultSymbol %>", "<%= Foil.address %>", "<%= CollateralAsset.Token.address %>", "<%= parseEther(settings.lowerBoundMultiplier) %>", "<%= parseEther(settings.upperBoundMultiplier) %>", "<%= settings.duration %>", "0", "<%= settings.totalVaults %>", "<%= settings.owner2 %>", "<%= settings.claimStatement %>" ]
depends = ['router.Foil', 'clone.CollateralAsset', 'var.settings']
