name="foil"
version="1.0.4"
preset="gas-weekly"

[var.settings]
deployer="0xdb5af497a73620d881561edb508012a5f84e9ba2"
owner="0x66aB20e98fcACfadB298C0741dFddA92568B5826"
feeRate = "10000" # 1%
assertionLiveness = "21600"
bondAmount = "5000000000"
claimStatement = "<%= stringToHex('The sum of gas used divided by the sum of base fees paid on Ethereum Mainnet across all blocks for the specified period, represented with 18 decimal places') %>"
minTradeSize = "10000"

# Integration addresses
optimisticOracleV3 = "0x2aBf1Bd76655de80eDB3086114315Eec75AF500c" # UMA Optimistic Oracle V3 
uniswapPositionManager = "0x03a520b32C04BF3bEEf7BEb72E919cf822Ed34f1" # Uniswap V3 NonfungiblePositionManager 
uniswapSwapRouter = "0xAf5ead464aFFB12dD4CDFB98c9D2C490194FE5d0" # Using our deployed SwapRouter // "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45" # Uniswap V3 SwapRouter 
uniswapQuoter = "0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a" # Uniswap V3 QuoterV2 

# tokens
wstETH = "0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452"
USDC = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
depends = []

[deploy.ConfigurationModule]
artifact="ConfigurationModule"
args=["<%= settings.deployer %>"]

[deploy.LiquidityModule]
artifact="LiquidityModule"

[deploy.UMASettlementModule]
artifact="UMASettlementModule"

[deploy.TradeModule]
artifact="TradeModule"

[deploy.NftModule]
artifact="NftModule"

[deploy.ViewsModule]
artifact="ViewsModule"

[deploy.ERC165Module]
artifact="ERC165Module"

[deploy.SettlementModule]
artifact="SettlementModule"

[router.Foil]
contracts=[
  "ConfigurationModule",
  "LiquidityModule",
  "UMASettlementModule",
  "TradeModule",
  "NftModule",
  "ViewsModule",
  "ERC165Module",
  "SettlementModule"
]
highlight=true

[invoke.initializeMarket]
target="Foil"
func="initializeMarket"
from="<%= settings.deployer %>"
args=[
  "<%= settings.owner %>",
  "<%= settings.wstETH %>",
  [],
  "<%= zeroAddress %>",
  "<%= settings.minTradeSize %>",
  { feeRate = "<%= settings.feeRate %>", assertionLiveness= "<%= settings.assertionLiveness %>", bondCurrency = "<%= settings.USDC %>", bondAmount = "<%= settings.bondAmount %>", uniswapPositionManager = "<%= settings.uniswapPositionManager %>", uniswapSwapRouter = "<%= settings.uniswapSwapRouter %>", uniswapQuoter = "<%= settings.uniswapQuoter %>", optimisticOracleV3 = "<%= settings.optimisticOracleV3 %>" }
]
depends=["router.Foil"]

# Weekly Epochs

# Epoch 1
# [invoke.createEpoch]
# target="Foil"
# func="createEpoch"
# from="<%= settings.owner %>"
# args=[
#   "1743465600", # April 1st
#   "1744070400", # April 7th
#   "79228162514264337593543950336", # 1
#   "-9200", # 0.4
#   "16000", # 4
#   "<%= stringToHex('april-gas-weekly-epoch-1') %>"
# ]
# depends=["invoke.initializeMarket"]

