name="foil"
version="1.0.3"
preset="ism-2025-04"

include = [
  "templates/generic-marketgroup.toml",
  "templates/buckets-for-five.toml"
]

[setting.claimStatement]
defaultValue = "<%= stringToHex('What will the ISM Manufacturing PMI reading be for April 2025?') %>"

[setting.marketStartingTime]
defaultValue = "1745586000"

[setting.marketEndingTime]
defaultValue = "1746109800"

[setting.bucket1Name]
defaultValue = "<%= stringToHex('bucket 1') %>"

[setting.bucket2Name]
defaultValue = "<%= stringToHex('bucket 2') %>"

[setting.bucket3Name]
defaultValue = "<%= stringToHex('bucket 3') %>"

[setting.bucket4Name]
defaultValue = "<%= stringToHex('bucket 4') %>"

[setting.bucket5Name]
defaultValue = "<%= stringToHex('bucket 5') %>"

