name="foil"
version="1.0.3"
preset="ppi-2025-04"

include = [
  "templates/generic-marketgroup.toml",
  "templates/buckets-for-six.toml"
]

[setting.claimStatement]
defaultValue = "<%= stringToHex('What will the month-over-month change in the U.S. Producer Price Index (PPI) be for April 2025?') %>"

[setting.marketStartingTime]
defaultValue = "1745586000"

[setting.marketEndingTime]
defaultValue = "1747314000"

[setting.bucket1Name]
defaultValue = "<%= stringToHex('bucket 1') %>"

[setting.bucket2Name]
defaultValue = "<%= stringToHex('bucket 2') %>"

[setting.bucket3Name]
defaultValue = "<%= stringToHex('bucket 3') %>"

[setting.bucket4Name]
defaultValue = "<%= stringToHex('bucket 4') %>"

[setting.bucket5Name]
defaultValue = "<%= stringToHex('bucket 5') %>"

[setting.bucket6Name]
defaultValue = "<%= stringToHex('bucket 6') %>"

